### ISSUE TITLE
OS error when using NodeMCU and mcp23017

### ISSUE THREAD

**Issue by alolivas** [cefn/micropython-mcp230xx#4]
When I use the example code on the library:
```
import mcp, machine

#To test that the mcp is there
i2c = machine.I2C(scl=machine.Pin(13), sda=machine.Pin(12))
address = hex(i2c.scan()[0])
print(address)

io = mcp.MCP23017(gpioScl=13, gpioSda=12)

outPins = list(range(10,16))
nextVals = {}
for pinNum in outPins:
    io.setup(pinNum, mcp.OUT)
    nextVals[pinNum] = True
io.output_pins(nextVals)

# monitors and prints some input pins
inPins = list(range(0,10))
for pinNum in inPins:
    io.setup(pinNum, mcp.IN)
while True:
    print(io.input_pins(inPins))`
```
I get the following error:
```
Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "/lib/mcp.py", line 56, in __init__
  File "/lib/mcp.py", line 156, in write_iodir
  File "/lib/mcp.py", line 67, in writeList
OSError: [Errno 110] ETIMEDOUT

MicroPython v1.9.4-8-ga9a3caad0 on 2018-05-11; ESP module with ESP8266
```
I have spent hours replicating what the library does but I can't spot the error.

Any idea why?

**Comment by cefn** [comment]
Hi, there @alolivas 

Sorry you've been having trouble getting the results you want. I'm guessing the timeout is literally that the attempt to read has taken so long (without receiving anything) that it's giving up.

I imagine you would get this result for example if you hadn't attached a chip at all - e.g. it's sent some kind of initialisation stanza and is expecting something back but gets nothing because there's no chip responding. Equally if the I2C connections haven't been made correctly, or the address is 'wired' incorrectly then no response would appear as expected so the read would 'time out'.

Hopefully for your particular board you've figured out which pins are which (there is often a mystifying  mapping between D0-10 and GPIO0-16 which you would need to figure out since the I2C configuration uses GPIOxx numbers not Dxx numbers). Usually the mapping is something like...
https://github.com/vgkits/vanguard/blob/master/modules/vgkits/board/nodemcu.py

As a workaround if you can't progress with Micropython, you could try using circuitpython following this guide, but changing the pins to match the preferred I2C pins for your ESP8266 board... 

https://learn.adafruit.com/using-mcp23008-mcp23017-with-circuitpython/overview

I've found that I could install circuitpython on various ESP platforms and hopefully your nodemcu using [vgkits-vanguard](https://pypi.org/project/vgkits-vanguard/) and the command...

```vanguard brainwash circuitpython```

...and you can go back to micropython later with

```vanguard brainwash micropython```

To get the MCPxxx to work with Circuitpython, you'll probably have to copy over the needed circuitpython libraries from...

https://github.com/adafruit/Adafruit_CircuitPython_Bundle/tree/master/libraries/drivers

 e.g... the .py files from

https://github.com/adafruit/Adafruit_CircuitPython_MCP230xx/
https://github.com/adafruit/Adafruit_CircuitPython_BusDevice/

These are very well-maintained and you have [volunteer Discord support](https://discordapp.com/channels/327254708534116352/327298996332658690) via https://www.adafruit.com/circuitpython

**Comment by dentex** [comment]
Hello!
I have the same problem, with the same board. 

    >>> io = mcp.MCP23017()
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "mcp.py", line 56, in __init__
    File "mcp.py", line 156, in write_iodir
    File "mcp.py", line 67, in writeList```

while if I call the full constructor:

    >>> io = mcp.MPC23017(address=0x20, gpioScl=5, gpioSda=4)
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    AttributeError: 'module' object has no attribute 'MPC23017'

I double and triple checked the connection...
Do you have any hint? How can I use the library?

Thanks.

**Comment by dentex** [comment]
I initially had the same problem, but a proper re-wiring fixed it. 
Thanks for the great library.
